print('----------- Naive Bayes -----------')
exec(open('NaiveBayes.py').read())
print('----------- Logistic Regression -----------')
print(' Testing Regulrization Constants')
exec(open('LogisticRegression.py').read())
print('----------- Perceptron -----------')
exec(open('perceptron.py').read())